name: new_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'


dependency_overrides:
  meta: 1.16.0
  analyzer: ^7.3.0

dependencies:
  flutter:
    sdk: flutter
  http: 1.3.0
  scoped_model: 2.0.0
  provider: 6.1.1
  gap: 3.0.1
  flutter_secure_storage: 9.2.4
  dio: ^5.8.0+1
  get_it: 8.0.3
  package_info_plus: 8.2.1
  device_info_plus: 11.3.0
  connectivity_plus: 6.1.3
  flutter_svg: 2.0.17
  pin_code_fields: 8.0.1
  flutter_switch: 0.3.2
  logger: 2.5.0
  local_auth: 2.3.0
  shared_preferences: 2.5.2
  dartz: 0.10.1
  device_manager: 0.0.2
  overlay_support: 2.1.0
  flutter_pin_code_fields: 2.2.0
  cached_network_image: 3.4.1
  fluttertoast: 8.2.12
  smooth_page_indicator: 1.2.1
  firebase_remote_config: 5.4.1
  firebase_core: 3.12.0
  qr_code_scanner: 1.0.1
  image_picker: ^1.1.2
  image: 4.5.3
  intl: 0.19.0
  percent_indicator: 4.2.4
  currency_text_input_formatter: 2.2.8



  cupertino_icons: ^1.0.8
  dart_mappable: ^4.4.0
  dart_mappable_builder: ^4.4.0
  build_runner: ^2.4.15
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/json/
    - .env

fonts:
   - family: Manrope
     fonts:
       - asset: assets/fonts/manrope-light.otf
         weight: 300
       - asset: assets/fonts/manrope-regular.otf
         weight: 400
       - asset: assets/fonts/manrope-medium.otf
         weight: 500
       - asset: assets/fonts/manrope-bold.otf
         weight: 700
       - asset: assets/fonts/manrope-extrabold.otf
         weight: 800
       - asset: assets/fonts/manrope-semibold.otf
         weight: 600
       - asset: assets/fonts/manrope-thin.otf
         weight: 200

